work_dir: ${hydra:runtime:cwd}

paths:
  processed:
    processed_data: ${work_dir}/data/processed

  raw:
    data: ${hydra:runtime.cwd}/data/raw/
    captions_zipped_file: ${hydra:runtime.cwd}/data/raw/http:/msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip/val2014.zip
    train_zipped_file: ${hydra:runtime.cwd}/data/raw/train2014.zip
    validation_zipped_file: ${hydra:runtime.cwd}/data/raw/val2014.zip
    annotations_zipped_file:  ${hydra:runtime.cwd}/data/raw/annotations_trainval2014.zip

    unzipped_main_folder_name: all_data
    unzipped_train_subfolder: ${hydra:runtime.cwd}/data/raw/all_data/train/train2014
    unzipped_val_subfolder: ${hydra:runtime.cwd}/data/raw/all_data/validation
    unzipped_train_val_subfolder: ${hydra:runtime.cwd}/data/raw/all_data/train/val2014
    unzipped_annotations_subfolder: ${hydra:runtime.cwd}/data/raw/all_data
    vocab_path: ${hydra:runtime.cwd}/data/processed/vocabulary.pkl

  train:
    # TRAIN DATA
    images_raw_train_train_data: ${hydra:runtime.cwd}/data/raw/all_data/train/train2014
    images_raw_train_val_data: ${hydra:runtime.cwd}/data/raw/all_data/train/val2014
    processed_images_data: ${hydra:runtime.cwd}/data/processed/train/

  val:
    # VALIDATION DATA
    raw_data: ${hydra:runtime.cwd}/data/raw/validation/
    processed_data: ${hydra:runtime.cwd}/data/processed/validation/
    images_raw_data: ${hydra:runtime.cwd}/data/raw/all_data/validation/radiology/images/
    images_processed_data: ${hydra:runtime.cwd}/data/processed/validation/images/
    kaggle_radiology_images: ${hydra:runtime.cwd}/data/raw/all_data/validation/radiology/images/
    kaggle_radiology_data: ${hydra:runtime.cwd}/data/raw/all_data/validation/radiology/valdata.csv
    kaggle_radiology_keywords: ${hydra:runtime.cwd}/data/raw/all_data/validation/radiology/keywords.txt

  test:
    # TEST DATA
    raw_data: ${hydra:runtime.cwd}/data/raw/test
    processed_data: ${hydra:runtime.cwd}/data/processed/test/
    images_raw_data: ${hydra:runtime.cwd}/data/raw/all_data/test/radiology/images/
    images_processed_data: ${hydra:runtime.cwd}/data/processed/test/images/
    kaggle_radiology_images: ${hydra:runtime.cwd}/data/raw/all_data/test/radiology/images/
    kaggle_radiology_data: ${hydra:runtime.cwd}/data/raw/all_data/test/radiology/testdata.csv
    kaggle_radiology_keywords: ${hydra:runtime.cwd}/data/raw/all_data/test/radiology/keywords.txt

params:
  max_text_tokens_length: 128
  microsoft_pretrained: 'microsoft/git-base-coco'
  salesforce_pretrained: 'Salesforce/blip-image-captioning-large'
  # text_backbone: 'bert-base-uncased'
  # image_backbone: 'google/vit-base-patch16-224'

  batch_size: 8
  max_epochs: 75
  max_bad_epochs: 9
  patience: 3
  factor: 0.1
  vocab_threshold: 4


tests:
  paths:
    processed_image: ../../data/processed/train/COCO_train2014_000000000009.jpg


